// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOfeZVGhx5WmHR_TzhbdoiuQTqYdowa0',
    appId: '1:715973105965:web:3b48e9af72834f4671dba4',
    messagingSenderId: '715973105965',
    projectId: 'chatterbox-firebase',
    authDomain: 'chatterbox-firebase.firebaseapp.com',
    storageBucket: 'chatterbox-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf4sKX7wPxSs8DyAOSw3uPSCaH23Iip-s',
    appId: '1:715973105965:android:62f956238f9a3d4f71dba4',
    messagingSenderId: '715973105965',
    projectId: 'chatterbox-firebase',
    storageBucket: 'chatterbox-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaVnEofcjBWisS8KEQEBAykHxOhhq1PEU',
    appId: '1:715973105965:ios:dfb7ef2379b4447271dba4',
    messagingSenderId: '715973105965',
    projectId: 'chatterbox-firebase',
    storageBucket: 'chatterbox-firebase.appspot.com',
    iosBundleId: 'com.example.chatterBox',
  );
}
